apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: livepeer/cuda-ssh-server:11.2.2-cudnn8-runtime-ubuntu18.04

      containers:
      - name: sshd
        image: livepeer/cuda-ssh-server:11.2.2-cudnn8-runtime-ubuntu18.04
        
        resources:
          requests:
            cpu: 1500m # The CPU unit is mili-cores. 500m is 0.5 cores
            memory: 4Gi
          limits:
            cpu: 3000m
            memory: 8Gi
            nvidia.com/gpu: 1

      affinity:
        nodeAffinity:
          # This will REQUIRE the Pod to be run on a system with a Pascal GPU
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu.nvidia.com/model
                operator: In
                values:
                  - Quadro_RTX_4000
              - key: failure-domain.beta.kubernetes.io/region
                operator: In
                values:
                  - ORD1
